apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: app-3-dev
spec:
  type: LoadBalancer
  selector:
    app: angular-app-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
